CREATE DATABASE Student; 
CREATE TABLE S36(Id INT PRIMARY KEY, Name VARCHAR(50),Age INT NOT NULL);
SELECT * FROM S36;
EXEC SP_RENAME 'S36','BATCH36';
ALTER TABLE BATCH36 ADD Subject VARCHAR(25);
ALTER TABLE BATCH36 ALTER COLUMN Subject VARCHAR(50);
ALTER TABLE BATCH36 DROP COLUMN SUBJECT;
SELECT * FROM BATCH36;
CREATE TABLE EMPLOYEE(Id INT PRIMARY KEY, Name VARCHAR(50), Age INT NOT NULL, Designation VARCHAR(50));
DROP TABLE EMPLOYEE;
TRUNCATE TABLE BATCH36;


